// User模型和InspectionReport模型的中英文字段映射表

/**
 * User模型字段映射表
 * key: 英文字段名
 * value: 中文意思
 */
export const userModelFieldMap = {
  id: '用户唯一ID',
  username: '用户名',
  email: '电子邮箱',
  phone_number: '电话号码',
//   password_hash: '密码哈希',
  nickname: '昵称',
  avatar: '头像',
  gender: '性别',
  birthday: '出生日期',
  address: '地址',
  bio: '个人简介',
  status: '账号状态',
  created_at: '创建时间',
  updated_at: '更新时间',
  last_login_at: '最后登录时间',
  last_logout_at: '最后注销时间',
//   deleted_at: '软删除时间',
  openid: '第三方登录标识',
  unionid: '第三方联合标识',
  member_level: '会员等级',
  ext_info: '扩展信息',
  position_name: '岗位名称',
  employment_type: '雇佣类型',
  hire_date: '入职日期',
  department_id: '部门ID',
  id_card_number: '身份证号',
  reset_token: '密码重置令牌',
  reset_token_expires: '令牌过期时间',
  verification_code: '邮箱验证码',
  verification_code_expires: '验证码过期时间'
};

/**
 * InspectionReport模型字段映射表
 * key: 英文字段名
 * value: 中文意思
 */
export const inspectionReportModelFieldMap = {
  id: 'ID',
  project_name: '工程名称',
  project_location: '工程地址',
  project_type: '工程类型',
  project_stage: '工程阶段',
  construction_unit: '建设单位',
  contractor: '施工单位',
  supervisor: '监理单位',
  witness_unit: '见证单位',
  remarks: '备注',
  client_unit: '委托单位',
  client_contact: '委托人',
  acceptance_date: '受理日期',
  commission_date: '委托日期',
  commission_code: '委托编号',
  salesperson: '业务员',
  inspection_unit: '检测单位',
  certificate_no: '资质证书编号',
  contact_address: '联系地址',
  contact_phone: '联系电话',
  inspection_object: '检测对象',
  object_part: '检测部位',
  object_spec: '对象规格',
  design_spec: '设计要求',
  inspection_type: '检验类型',
  inspection_items: '检测项目',
  test_items: '检测项详情',
  inspection_quantity: '检测数量',
  measurement_unit: '计量单位',
  inspection_conclusion: '检测结论',
  conclusion_description: '结论描述',
  is_recheck: '是否复检',
  sampling_method: '抽样方式',
  sampling_date: '抽样日期',
  sampler: '抽样人员',
  start_date: '开始日期',
  end_date: '结束日期',
  inspection_code: '检测编号',
  inspector: '检测员',
  tester_date: '检测完成日期',
  reviewer: '审核人',
  review_date: '审核日期',
  approver: '批准人',
  approve_date: '批准日期',
  report_date: '报告日期',
  issue_date: '签发日期',
  report_code: '报告编号',
  report_status: '报告状态',
  qrcode_content: '二维码内容',
  attachment_paths: '附件路径',
  created_at: '创建时间',
  updated_at: '更新时间',
  registrant: '登记人',
  registrant_id: '登记人ID',
  last_modified_by_id: '最后修改人ID',
  last_modified_by: '最后修改人',
  // is_deleted: '软删除标记'
};